### ISSUE TITLE
character maps to <undefined> error on version 84

### ISSUE THREAD

**Issue by Numenorean** [P1sec/hermes-dec#1]
The full error message is `UnicodeEncodeError: 'charmap' codec can't encode character '\u2502' in position 68: character maps to <undefined>` which happens while printing instructions. As from the readme, you tested on the same version and it seems you have it worked. Any suggestions?

**Comment by p1-mmr** [comment]
Hello,

Can your please share your sample .HBC file on this issue, or at ![image](https://user-images.githubusercontent.com/26739350/219876243-4cc6e6db-e2b5-474d-b822-45167b133539.png) if you wish to keep it private?

Thank you!

**Comment by p1-mmr** [comment]
Hello,

Can your please share your sample .HBC file on this issue, or at ![image](https://user-images.githubusercontent.com/26739350/219876243-4cc6e6db-e2b5-474d-b822-45167b133539.png) if you wish to keep it private?

Thank you!

**Comment by p1-mmr** [comment]
Additionally, can you please specify which operating system version, terminal/command prompt and Python version you are using, and copy the full traceback associated with the error? (This error seems to be chiefly related with Windows-based environments) 

Thank you

**Comment by Numenorean** [comment]
I'm sorry for taking that long to respond. I forgot to write the solution to the issue. I have solved the same way as you did, thanks. That helped with my sample
