### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by praetorian-tim** [P1sec/hermes-dec#3]
Hello,

I wanted to reach out and make you aware of a typo I noticed in the file README.md:
https://github.com/P1sec/hermes-dec/blob/7444ad2879fdda949148e8ac0e91a393038bcad9/README.md?plain=1#L74

The folder which holds the decompilation tools is currently "decompilation", not "decompiler". As such, the command could be updated as follows:

`~/hermes-dec/decompilation/hbc_decompiler.py assets/index.android.bundle /tmp/my_output_file.js`

A very small issue overall, but I figured it may be worth bringing up.

Thank you, and I appreciate the hard work spent developing this tool!

**Comment by p1-mmr** [comment]
Thank you!
