### ISSUE TITLE
Incorrect decompilation of `Not` opcode

### ISSUE THREAD

**Issue by aamiaa** [P1sec/hermes-dec#7]
The `Not` opcode should use the `!` operator, meanwhile it uses the `-` operator
https://github.com/P1sec/hermes-dec/blob/2bd5073066a4917a7b91d7635c07a449e1245b56/src/decompilation/pass2_transform_code.py#L489-L490

**Comment by p1-mmr** [comment]
Fixed in commit 1a3de1c, thanks!
